import { useMemo } from 'react'
import { useSearchParams } from 'react-router-dom'
import PresentationDeck from '../components/present/PresentationDeck.jsx'
import { MISSIONS } from '../missions/missions.js'
import { processRunsForMission } from '../hooks/usePresentationDeckData.js'

/**
 * /rescue?d=<base64>
 *
 * Standalone admin rescue presentation screen.
 * Reads ALL data from the URL — no Supabase reads, no team session,
 * completely independent of whatever the team is doing on their link.
 *
 * The `d` param is a base64url-encoded JSON blob generated by AdminScreen:
 * {
 *   sessionCode: string,
 *   missionId: string,
 *   runs: RunRow[],          // raw DB run rows
 *   notes: { approach, broke, concept }
 * }
 */
export default function RescuePresentScreen() {
    const [params] = useSearchParams()
    const raw = params.get('d')

    const payload = useMemo(() => {
        if (!raw) return null
        try {
            const b64 = raw.replace(/-/g, '+').replace(/_/g, '/')
            const json = decodeURIComponent(escape(atob(b64)))
            return JSON.parse(json)
        } catch {
            return null
        }
    }, [raw])

    if (!raw) {
        return (
            <main className="min-h-screen bg-bg0 text-text0 flex flex-col items-center justify-center p-8 gap-4">
                <div className="font-['Syne'] text-2xl font-bold text-amber">🛟 Rescue Presentation</div>
                <p className="text-text2 text-sm text-center max-w-md">
                    This page is opened automatically from the Admin panel using the{' '}
                    <span className="font-mono text-amber">Rescue Deck</span> button.
                </p>
            </main>
        )
    }

    if (!payload) {
        return (
            <main className="min-h-screen bg-bg0 text-text0 flex flex-col items-center justify-center p-8 gap-4">
                <div className="font-['Syne'] text-2xl font-bold text-red">Invalid rescue link</div>
                <p className="text-text2 text-sm">The payload could not be decoded. Use the admin panel to regenerate.</p>
            </main>
        )
    }

    const mission = MISSIONS.find(m => m.id === payload.missionId) ?? MISSIONS[0]
    const processedRuns = processRunsForMission(payload.runs || [], mission)
    const bestRun = processedRuns.length > 0
        ? processedRuns.reduce((best, run) =>
            (run.final_accuracy || 0) > (best.final_accuracy || 0) ? run : best)
        : null

    return (
        <PresentationDeck
            variant="projector"
            teamName={`${payload.sessionCode} — Instructor Walkthrough`}
            sessionCode={payload.sessionCode}
            mission={mission}
            allRuns={processedRuns}
            bestRun={bestRun}
            notes={payload.notes || { approach: '', broke: '', concept: '' }}
            hideBadges={true}
        />
    )
}
